  # This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    tags:
      - v**
  workflow_dispatch:


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Git pull
        run: git pull
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Check PDF file
        run: |
          file 'main.pdf' | grep -q ' PDF '
      - name: Rename PDF file
        run: |
          mv 'main.pdf' 'statuto.pdf'
      - uses: actions/upload-artifact@v3
        with:
          name: statuto
          path: statuto.pdf
          retention-days: 180
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            statuto.pdf
          tag_name: statuto_${{github.ref_name}}.pdf
