  # This is a basic workflow to help you get started with Actions

name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - '**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Git pull
        run: git pull
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Check PDF file
        run: |
          file 'main.pdf' | grep -q ' PDF '
      - name: Rename PDF file
        run: |
          mv 'main.pdf' 'Document.pdf'
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f "Document.pdf"
          git commit -m "📙 Update document pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'document'
          force: true
